"""update models

Revision ID: 0e38459fb5d2
Revises: 
Create Date: 2021-07-16 11:43:11.836686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e38459fb5d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Text(), nullable=False),
    sa.Column('course_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id')
    )
    op.create_table('interests',
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.Column('interest_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('interest_id'),
    sa.UniqueConstraint('interest_name')
    )
    op.create_table('networking_goals',
    sa.Column('networking_goal_id', sa.Integer(), nullable=False),
    sa.Column('networking_goal', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('networking_goal_id'),
    sa.UniqueConstraint('networking_goal')
    )
    op.create_table('time_options',
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('time_option', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('time_id'),
    sa.UniqueConstraint('time_option')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('firstname', sa.Text(), nullable=True),
    sa.Column('lastname', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('cohort', sa.Text(), nullable=True),
    sa.Column('linkedin', sa.Text(), nullable=True),
    sa.Column('course_id_to_match', sa.Integer(), nullable=True),
    sa.Column('interest_id_to_match', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id_to_match'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['interest_id_to_match'], ['interests.interest_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_username'), 'students', ['username'], unique=True)
    op.create_table('current_courses_record',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    op.create_table('past_courses_record',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    op.create_table('student_interest_record',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.interest_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'interest_id')
    )
    op.create_table('weekly_signups',
    sa.Column('weekly_signup_id', sa.Integer(), nullable=False),
    sa.Column('week_meet', sa.Text(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('prime_time_id', sa.Integer(), nullable=False),
    sa.Column('sec_time_id', sa.Integer(), nullable=False),
    sa.Column('prime_networking_goal_id', sa.Integer(), nullable=False),
    sa.Column('sec_networking_goal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prime_networking_goal_id'], ['networking_goals.networking_goal_id'], ),
    sa.ForeignKeyConstraint(['prime_time_id'], ['time_options.time_id'], ),
    sa.ForeignKeyConstraint(['sec_networking_goal_id'], ['networking_goals.networking_goal_id'], ),
    sa.ForeignKeyConstraint(['sec_time_id'], ['time_options.time_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('weekly_signup_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_signups')
    op.drop_table('student_interest_record')
    op.drop_table('past_courses_record')
    op.drop_table('current_courses_record')
    op.drop_index(op.f('ix_students_username'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    op.drop_table('time_options')
    op.drop_table('networking_goals')
    op.drop_table('interests')
    op.drop_table('courses')
    # ### end Alembic commands ###
