"""add unique constraint to course_id

Revision ID: 250d3fa8563e
Revises: 4558a107f61b
Create Date: 2021-07-23 10:23:08.229967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250d3fa8563e'
down_revision = '4558a107f61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'courses', ['course_id'])
    op.alter_column('weekly_signups', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'weekly_signups', 'students', ['student_id'], ['student_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weekly_signups', type_='foreignkey')
    op.alter_column('weekly_signups', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'courses', type_='unique')
    # ### end Alembic commands ###
