"""changed course_id types

Revision ID: 2db52e11a597
Revises: 250d3fa8563e
Create Date: 2021-07-23 10:29:16.948084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db52e11a597'
down_revision = '250d3fa8563e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_courses_record',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    op.create_table('past_courses_record',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    op.add_column('students', sa.Column('course_id_to_match', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'students', 'courses', ['course_id_to_match'], ['course_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'course_id_to_match')
    op.drop_table('past_courses_record')
    op.drop_table('current_courses_record')
    # ### end Alembic commands ###
