"""new tables

Revision ID: 4ca906d42cb1
Revises: 
Create Date: 2021-07-28 09:00:42.819375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca906d42cb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'courses', ['course_id'])
    op.create_unique_constraint(None, 'students', ['student_id'])
    op.create_unique_constraint(None, 'unmatched_students', ['student_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unmatched_students', type_='unique')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'courses', type_='unique')
    # ### end Alembic commands ###
