"""update unmatchedstudents

Revision ID: 890cd158df28
Revises: d73981ef6678
Create Date: 2021-07-27 15:37:25.265273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890cd158df28'
down_revision = 'd73981ef6678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unmatched_students_email', table_name='unmatched_students')
    op.drop_column('unmatched_students', 'last_name')
    op.drop_column('unmatched_students', 'first_name')
    op.drop_column('unmatched_students', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unmatched_students', sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('unmatched_students', sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('unmatched_students', sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_unmatched_students_email', 'unmatched_students', ['email'], unique=False)
    # ### end Alembic commands ###
