"""add relationship between meeting and timeopt

Revision ID: d73981ef6678
Revises: 2db52e11a597
Create Date: 2021-07-23 11:13:49.116530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73981ef6678'
down_revision = '2db52e11a597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'time_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'meetings', 'time_options', ['time_id'], ['time_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.alter_column('meetings', 'time_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
