"""empty message

Revision ID: eb07648804bd
Revises: 
Create Date: 2021-08-18 21:22:43.340090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb07648804bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'students', ['student_id'])
    op.create_unique_constraint(None, 'unmatched_students', ['student_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unmatched_students', type_='unique')
    op.drop_constraint(None, 'students', type_='unique')
    # ### end Alembic commands ###
